### PR TITLE
Sadly Firefox for Android doesn't support Intl APIs

### PR DESCRIPTION
**Pull request by julienw**

### CODE REVIEW

**Comment by ericf** [comment]
Do you know if there's any plans to eventually support the `Intl` APIs in Firefox for Android?

**Comment by julienw** [comment]
Yeah, the bug to follow is https://bugzilla.mozilla.org/show_bug.cgi?id=1215247.

There is a green light for landing to Nightly but this hadn't been done yet.

**Comment by ericf** [comment]
Okay. When it lands, if you wouldn't mind sending another PR to revert this change, that would be awesome!

**Comment by julienw** [comment]
I'll try to remember :) Thanks !

**Comment by julienw** [comment]
It just landed in Nightly: https://bugzilla.mozilla.org/show_bug.cgi?id=1215247

When do you think the documentation should be updated ? When it reaches stable ?

**Comment by ericf** [comment]
Yeah when it reaches Stable sounds like a good plan. Thanks for following up!

**Comment by julienw** [comment]
So it's still not planned to be in the release version. It's enabled in Nightly only for now.
https://bugzilla.mozilla.org/show_bug.cgi?id=1344625 is the new tracking bug.

**Pull request merged**
