### PR TITLE
Happy new year!

### PR DESCRIPTION
**Pull request by DavidLemayian**
Just a tiny footer change. :)

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by caridy** [comment]
@DavidLemayian thanks for the PR, make sure you sign the CLA.

As for the copyright update, there is not need to do so, in fact is it recommended to stamp the date of the file creation, and that is sufficient for the copyright.

**Comment by DavidLemayian** [comment]
@caridy Interesting, always figured copyright year would be more likely to be affected with change in content. But that is definitely an angle I haven't encountered before.

Will look at the CLA.

**Comment by DavidLemayian** [comment]
@yahoocla @caridy Well this is awkward.. Just got the following error when I tried to sign in with Github on the CLA page:

```
Error: no open connections
   at Db._executeQueryCommand (/app/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/db.js:1802:21)
   at Db.obj.(anonymous function) [as _executeQueryCommand] (/app/node_modules/nodetime/lib/core/proxy.js:45:19)
   at Cursor.nextObject (/app/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/cursor.js:729:13)
   at Cursor.nextObject (/app/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/scope.js:22:20)
   at Collection.findOne (/app/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/collection/query.js:145:10)
   at /app/node_modules/connect-mongo/lib/connect-mongo.js:214:18
   at MongoStore._get_collection (/app/node_modules/connect-mongo/lib/connect-mongo.js:148:21)
   at MongoStore.get (/app/node_modules/connect-mongo/lib/connect-mongo.js:213:10)
   at session (/app/node_modules/express-session/index.js:324:11)
   at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:76:5)
```

**Pull request closed without merging**
