### PR TITLE
ember-intl - hiding download button, removing defaultLocale in example

### LINKED ISSUE #169: Remove defaultLocale from emberjs integration
Remove defaultLocale from emberjs integration.  This will remain an undocumented feature and likely be removed after 1.0.0

I thought this was handled yesterday, it's still there.  Perhaps bad merge?

### PR DESCRIPTION
**Pull request by jasonmit**
Fixes #169 #168

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by ericf** [comment]
What if we added this to `lib/package-meta.js`?

We could add some `hasDownload` metadata that's set to `true`. for Ember Intl it could look like:

```js
var pkgMeta = require('../lib/package-meta')('ember-intl', {
    distPath: path.join('ember-intl', 'packaging', 'dist'),
    hasDownload: false
});
```

I think that would be cleaner, and in the `package-meta.hbs` partial template there would be a `package.hasDownload`.

**Comment by jasonmit** [comment]
Sounds good, I wasn't too sure which object this property should hang off

**Comment by jasonmit** [comment]
@ericf change made

**Pull request merged**
