### PR TITLE
Fix French sentence in the splash example

### LINKED ISSUE #193: French sentence is wrong
On the French homepage:
Wrong: "Le ‎15‎ ‎avril‎ ‎2015, Annie n'a pas pris de photographi<b>es</b>"
Shoud be: "Le ‎15‎ ‎avril‎ ‎2015, Annie n'a pas pris de photographi<b>e</b>"

### PR DESCRIPTION
**Pull request by okuryu**
Fix #193.

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by caridy** [comment]
+1 but, lets cc @jlecomte, who is the authority when it comes to french, jejejeje.

**Comment by caridy** [comment]
ah, this came from @jlecomte in the first place. I guess I am not reading the github notification in the right order, jejejeje. Let's roll!

**Comment by okuryu** [comment]
Yup yup! Thanks @caridy!

**Pull request merged**
